### ISSUE TITLE
Plugin unavailable and needs an update

### ISSUE THREAD

**Issue by AndyGy** [TimOosterom/TombsOfAmascutHelper#3]
Hi Tim,

the plugin is showing unvailable for me and saying it needs an update

could you looks into please because your plugin helps me alot

thank you in advance

![image](https://github.com/TimOosterom/TombsOfAmascutHelper/assets/40192462/25ba25bb-8d9f-479c-bf05-e65945efff35)
![Toa Helper](https://github.com/TimOosterom/TombsOfAmascutHelper/assets/40192462/e84eff3b-dc57-4e7d-99db-f8e511e735b0)

**Comment by TimOosterom** [comment]
Should be working again now
